version: '3'

services:
  openldap:
    image: osixia/openldap:1.5.0
    hostname: openldap.confluentdemo.io
    container_name: openldap
    environment:  
        LDAP_ORGANISATION: "Confluent Demo"
        LDAP_DOMAIN: "confluentdemo.io"
        LDAP_BASE_DN: "dc=confluentdemo,dc=io"
        LDAP_TLS_CRT_FILENAME: "openldap-fullchain.pem"
        LDAP_TLS_KEY_FILENAME: "openldap.key"
        LDAP_TLS_CA_CRT_FILENAME: "ca.pem"
        LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
        - ../../generated/ssl:/container/service/slapd/assets/certs
        - ./openldap/ldifs:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service --loglevel debug"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    hostname: zookeeper.confluentdemo.io
    environment:
      ZOO_TLS_QUORUM_ENABLE: true
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SECURE_CLIENT_PORT: 2182
      ZOOKEEPER_SERVER_CNXN_FACTORY: org.apache.zookeeper.server.NettyServerCnxnFactory
      ZOOKEEPER_SSL_KEYSTORE_LOCATION: /mnt/ssl/zookeeper.keystore.jks
      ZOOKEEPER_SSL_KEYSTORE_PASSWORD: topsecret
      ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/zookeeper.truststore.jks
      ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: topsecret
      ZOOKEEPER_AUTH_PROVIDER_X509: org.apache.zookeeper.server.auth.X509AuthenticationProvider
    volumes:
      - ../../generated/ssl:/mnt/ssl

  kafka:
    image: confluentinc/cp-server:7.4.0
    container_name: kafka
    hostname: kafka.confluentdemo.io
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.confluentdemo.io:2182
      KAFKA_ZOOKEEPER_SSL_CLIENT_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CLIENT_CNXN_SOCKET: org.apache.zookeeper.ClientCnxnSocketNetty
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_LOCATION: /mnt/ssl/kafka.keystore.jks
      KAFKA_ZOOKEEPER_SSL_KEYSTORE_PASSWORD: topsecret
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/kafka.truststore.jks
      KAFKA_ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD: topsecret
      KAFKA_ZOOKEEPER_SET_ACL: 'true'

      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka.confluentdemo.io:9092
      KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_LOCATION: /mnt/ssl/kafka.keystore.jks
      KAFKA_LISTENER_NAME_INTERNAL_SSL_KEYSTORE_PASSWORD: topsecret
      KAFKA_LISTENER_NAME_INTERNAL_SSL_KEY_PASSWORD: topsecret
      KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/kafka.truststore.jks
      KAFKA_LISTENER_NAME_INTERNAL_SSL_TRUSTSTORE_PASSWORD: topsecret
      KAFKA_LISTENER_NAME_INTERNAL_SSL_CLIENT_AUTH: required
      KAFKA_LISTENER_NAME_INTERNAL_SECURITY_PROTOCOL: SSL
      KAFKA_LISTENER_NAME_INTERNAL_SSL_PRINCIPAL_MAPPING_RULES: RULE:^CN=([a-zA-Z0-9.]*).*$$/$$1/ , DEFAULT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SECURITY_EVENT_LOGGER_EXPORTER_KAFKA_TOPIC_REPLICAS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_HEAL_BROKER_FAILURE_THRESHOLD_MS: 30000
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka.confluentdemo.io:9092
      CONFLUENT_METRICS_REPORTER_SECURITY_PROTOCOL: SSL
      CONFLUENT_METRICS_REPORTER_MAX_REQUEST_SIZE: 10485760
      CONFLUENT_METRICS_REPORTER_TOPIC_CREATE: 'true'
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_LOCATION: /mnt/ssl/kafka.keystore.jks
      CONFLUENT_METRICS_REPORTER_SSL_KEYSTORE_PASSWORD: topsecret
      CONFLUENT_METRICS_REPORTER_SSL_KEY_PASSWORD: topsecret
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/kafka.truststore.jks
      CONFLUENT_METRICS_REPORTER_SSL_TRUSTSTORE_PASSWORD: topsecret
    volumes:
      - ../../generated/ssl:/mnt/ssl
      
  controlcenter:
    image: confluentinc/cp-enterprise-control-center:7.4.0
    hostname: controlcenter.confluentdemo.io
    container_name: controlcenter
    healthcheck:
      start_period: 10s
      interval: 10s
      retries: 20
      test: curl -k --fail --silent https://control-center:9021 --output /dev/null || exit 1
    depends_on:
      - kafka
    volumes:
      - ../../generated/ssl:/mnt/ssl
    ports:
      - 9021:9021
    environment:
      CUB_CLASSPATH: '/usr/share/java/confluent-control-center/*:/usr/share/java/rest-utils/*:/usr/share/java/confluent-common/*:/usr/share/java/confluent-security/kafka-rest/*:/usr/share/java/kafka-rest/:/usr/share/java/cp-base-new/*'
      CONTROL_CENTER_BOOTSTRAP_SERVERS: SSL://kafka.confluentdemo.io:9092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SSL
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 1
      CONTROL_CENTER_METRICS_TOPIC_PARTITIONS: 1
      CONTROL_CENTER_STREAMS_CACHE_MAX_BYTES_BUFFERING: 100000000
      CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
      CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 1
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/controlcenter.truststore.jks
      CONTROL_CENTER_STREAMS_SSL_TRUSTSTORE_PASSWORD: topsecret
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_LOCATION: /mnt/ssl/controlcenter.keystore.jks
      CONTROL_CENTER_STREAMS_SSL_KEYSTORE_PASSWORD: topsecret
      CONTROL_CENTER_STREAMS_SSL_KEY_PASSWORD: topsecret
      CONTROL_CENTER_REST_LISTENERS: https://0.0.0.0:9021
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_LOCATION: /mnt/ssl/controlcenter.truststore.jks
      CONTROL_CENTER_REST_SSL_TRUSTSTORE_PASSWORD: topsecret
      CONTROL_CENTER_REST_SSL_KEYSTORE_LOCATION: /mnt/ssl/controlcenter.keystore.jks
      CONTROL_CENTER_REST_SSL_KEYSTORE_PASSWORD: topsecret
      CONTROL_CENTER_REST_SSL_KEY_PASSWORD: topsecret
      PORT: 9021
      CONTROL_CENTER_OPTS: "-Djava.security.auth.login.config=/mnt/ssl/c3-ldap-jaas.conf"
      CONTROL_CENTER_REST_AUTHENTICATION_REALM: c3
      CONTROL_CENTER_REST_AUTHENTICATION_METHOD: BASIC
      CONTROL_CENTER_AUTH_RESTRICTED_ROLES: ""
      CONTROL_CENTER_REST_AUTHENTICATION_ROLES: "confluentcomponents"
      CONTROL_CENTER_SCHEMA_REGISTRY_ENABLE: "false"
      CONTROL_CENTER_KSQL_ENABLE: "false"